### ISSUE TITLE
Cannot read property 'createSwaggerPage' of undefined after updating

### ISSUE THREAD

**Issue by MathieuDoyon** [RemyJeancolas/restify-swagger-jsdoc#4]
my package.json` have this `"restify-swagger-jsdoc": "^1.0.8"`

The build is now broken since it install *1.1.0* this tag. It should have been tagged 2.0.0 instead.

**Comment by RemyJeancolas** [comment]
A _2.0.0_ tag would be a bit overkill I think, the issue is related to the way you include the module in Typescript, using `import restifySwaggerJsdoc from 'restify-swagger-jsdoc';`

You should have used `import * as restifySwaggerJsdoc from 'restify-swagger-jsdoc';` to solve this issue, anyway I just pushed a patch (v1.1.1) which has a default export that should fix your problem.
``
Let me know if it works for you.

**Comment by RemyJeancolas** [comment]
@MathieuDoyon I created a new tag to switch back to swagger-ui v2, v3 doesn't seem enough mature for now.
You can use the last version (1.1.2) of the module.
