### ISSUE TITLE
vulnerability updates

### ISSUE THREAD

**Issue by acommodari** [RemyJeancolas/restify-swagger-jsdoc#46]
Hello just wanted to follow up on both these PRs:
#45 
#40 

I just wanted to know when you planned to merge either of these so I could plan accordingly.

Thanks!

**Comment by acommodari** [comment]
Hey 😄 just checking up to see if there are any updates on this?

**Comment by acommodari** [comment]
@RemyJeancolas  hey just checking in again to see if there was any way we could address the vulnerabilities of this package.
If you would prefer I create a PR I could be down to do that as well 👍

**Comment by acommodari** [comment]
So I am currently working on updating the repos dependencies and I was wondering... you currently support `node` v8 and above but 8, 10, 12 are now dropped. Do you still want to support such old versions of `node`? If you are okay with dropping them (at least node 8 and 10) then it would be possible to update most of your dependencies to their latest versions since they themselves no longer support such old node versions.

Let me know 😄 right now I'm updating dependencies while making sure they still support v8

**Comment by RemyJeancolas** [comment]
First, thanks for the PR 👍 
I just merged it and published a new version (`v3.3.0`) on npm.

Regarding the currently supported versions, I'm ok dropping support for node 8 and 10 since they are not supported anymore, node 12 is in EOL but still maintained so I'd like to keep it for now.
![image](https://user-images.githubusercontent.com/10399563/165775904-bd5cb0a8-411d-418c-9303-9a7bba16410c.png)

This will require to create a new major version but it's not a big deal.
I don't have a lot of time at the moment to update the dependencies, but you are welcome to submit another PR without support for node 8 and 10 and updated dependencies.
Thank you again for your help 😄
